version: '3'
services:
  node1:
    build: .
    ports:
      - "8081:8080"
      - "9091:9090"
    command: ["node1", "node1", "8080", "9090", "node2:8080,node3:8080"]
  node2:
    build: .
    ports:
      - "8082:8080"
      - "9092:9090"
    command: ["node2", "node2", "8080", "9090", "node1:8080,node3:8080"]
  node3:
    build: .
    ports:
      - "8083:8080"
      - "9093:9090"
    command: ["node3", "node3", "8080", "9090", "node1:8080,node2:8080"]